language: go
# Only clone the most recent commit.
git:
  depth: 1
go:
- 1.10.x
- 1.11.x
- 1.12.x

env:
  - CGO_ENABLED=0 GO111MODULE=on

before_install:
  - go get -t -v ./...
script:
  - diff -u <(echo -n) <(gofmt -d .)
  - pwd
  - ll
  - go build ./...
  - ./felix -h
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - neochau@gmail.com
    on_success: never